target_compatible_with = ["prelude//os:windows"]
omit_deps = [
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]

['cfg(target_os = "windows")']
cfgs = ["windows_raw_dylib"]
