name: Release

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package sources into tar.gz
        run: git ls-tree -r --name-only HEAD | xargs tar --transform "s#^#${{github.event.repository.name}}-${{github.event.release.tag_name}}/#" -czf ${{github.event.repository.name}}-${{github.ref_name}}.tar.gz
      - name: Upload release archive
        run: gh release upload ${{github.ref_name}} ${{github.event.repository.name}}-${{github.ref_name}}.tar.gz
        env:
          GH_TOKEN: ${{github.token}}
